version: '3.1'

services:
  node:
    image: "node:18"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=desenvolviment
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "yarn test"
    
